version: '3'
services:
  app:
    build: .
    image: alpeza/hcilinkweb:latest
    ports:
      - '84:80'
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5000
      - DATABASE_LINKS=/app/backend/db/links.json
    volumes:
      - ./ldb:/app/backend/db
    networks:
      - core_npm_hcinet

networks:
  core_npm_hcinet:
    external: true
